name: quasar-chat CI
on:
  push:
    tags:
      - '*'
jobs: 
    build-and-publish: 
        name: clone, test build docker quasar-chat
        runs-on: ubuntu-latest 
        steps: 
            - name: setup node 
              uses: actions/setup-node@v1 
              with: 
                node-version: '12.0' 
            - name: checkout quasar-chat 
              uses: actions/checkout@v2 
              with: 
                repository: ewol123/quasar-chat 
                ref: master   #specify branch here 
                token: ${{ secrets.WORKFLOW }} #save secret in quasar-chat repository 
                path: quasar-chat  #we can access this folder in our workspace 
            - name: npm install quasar-chat 
              working-directory: quasar-chat 
              run: npm install 
            - name: lint quasar-chat 
              working-directory: quasar-chat 
              run: npm run lint-fix
            - name: get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: docker build quasar-chat
              working-directory: quasar-chat
              run: docker build -t gyulavaripeter/quasar-chat:latest -t gyulavaripeter/quasar-chat:${{ steps.get_version.outputs.VERSION }} .
            - name: docker login
              env:
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - name: docker push latest
              run: docker push gyulavaripeter/quasar-chat:latest
            - name: docker push version
              run: docker push gyulavaripeter/quasar-chat:${{ steps.get_version.outputs.VERSION }}
            - name: commit changes to repository 
              uses: stefanzweifel/git-auto-commit-action@v4 
              with: 
                commit_message: Apply automatic changes 
                branch: master 
                commit_options: '--no-verify --signoff' 
                repository: quasar-chat