name: quasar-chat CI
on:
  push:
    branches:
      - stg
jobs: 
    build-and-publish: 
        name: clone, test build docker quasar-chat
        runs-on: ubuntu-latest 
        steps: 
            - name: setup node 
              uses: actions/setup-node@v1 
              with: 
                node-version: '12.0' 
            - name: docker login
              env:
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - name: start testing redis db
              run: docker run --name redis -p6379:6379 -d redis redis-server --appendonly yes
            - name: start testing postgres db
              run: docker run --name postgres -p5432:5432 -e POSTGRES_PASSWORD=test -e POSTGRES_USER=postgres -e POSTGRES_DB=chat-stg -d postgres
            - name: start testing server
              run: docker run --name chat-service --link redis:redis --link postgres:postgres -p3001:3001 -e REDIS_HOST=redis -e REDIS_PORT=6379 -e PG_HOST=postgres -e PG_PORT=5432 -e PG_USER=postgres -e PG_PW=test -e PG_DB=chat-stg -d gyulavaripeter/chat-service:latest
            - name: wait for server to start
              uses: jakejarvis/wait-action@master
              with:
                time: '30s'
            - name: checkout quasar-chat 
              uses: actions/checkout@v2 
              with: 
                repository: ewol123/quasar-chat 
                ref: stg   #specify branch here 
                token: ${{ secrets.WORKFLOW }} #save secret in quasar-chat repository 
                path: quasar-chat  #we can access this folder in our workspace 
            - name: npm install quasar-chat 
              working-directory: quasar-chat 
              run: npm install 
            - name: lint quasar-chat 
              working-directory: quasar-chat 
              run: npm run lint-fix
            - name: get the commit sha
              working-directory: quasar-chat
              id: get_sha
              run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short HEAD)
            - name: docker build quasar-chat-testing
              working-directory: quasar-chat
              run: docker build -f Dockerfile-dev -t gyulavaripeter/quasar-chat-testing:latest .
            - name: run quasar-chat for testing
              run: docker run --name quasar-chat --network=host -p82:82 -d gyulavaripeter/quasar-chat-testing:latest
            - name: test quasar-chat
              working-directory: quasar-chat 
              run: npm run local-test
              env:
                BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
                BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
                BROWSERSTACK_PORT: 82
            - name: docker build quasar-chat
              working-directory: quasar-chat
              run: docker build -t gyulavaripeter/quasar-chat:latest -t gyulavaripeter/quasar-chat:stg-${{ steps.get_sha.outputs.COMMIT_SHA }} .
            - name: docker push latest
              run: docker push gyulavaripeter/quasar-chat:latest
            - name: docker push COMMIT_SHA
              run: docker push gyulavaripeter/quasar-chat:stg-${{ steps.get_sha.outputs.COMMIT_SHA }}
            - name: commit changes to repository 
              uses: stefanzweifel/git-auto-commit-action@v4 
              with: 
                commit_message: Apply automatic changes 
                branch: stg 
                commit_options: '--no-verify --signoff' 
                repository: quasar-chat